# - Try to find SDL2
# Once done this will define
#
#  WITH_SDL - system has SDL2
#  SDL_INCLUDE_DIR - the SDL2 include directory
#  SDL_LIBRARIES - Link these to use SDL2
#

IF (SDL_INCLUDE_DIR AND SDL_LIBRARIES)
  # Already in cache, be silent
  SET(SDL_FIND_QUIETLY TRUE)
ELSE (SDL_INCLUDE_DIR AND SDL_LIBRARIES)
  FIND_LIBRARY(SDL_LIBRARIES NAMES SDL2)
  FIND_PATH(SDL_INCLUDE_DIR NAMES SDL2)
ENDIF (SDL_INCLUDE_DIR AND SDL_LIBRARIES)

IF (SDL_INCLUDE_DIR AND SDL_LIBRARIES)
  SET(WITH_SDL TRUE)
ENDIF (SDL_INCLUDE_DIR AND SDL_LIBRARIES)

IF (WITH_SDL)
  IF (NOT SDL_FIND_QUIETLY)
    MESSAGE(STATUS "Found SDL: ${SDL_LIBRARIES}")
  ENDIF (NOT SDL_FIND_QUIETLY)

  ADD_DEFINITIONS(-DWITH_SDL -DWITH_CONTROLLER_SUPPORT)
ELSE (WITH_SDL)
  IF (SDL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SDL")
  ENDIF (SDL_FIND_REQUIRED)

  SET(SDL_INCLUDE_DIR "")
  SET(SDL_LIBRARIES "")
ENDIF (WITH_SDL)

mark_as_advanced(
        SDL_INCLUDE_DIR
        SDL_LIBRARIES
)